# Generated by Django 3.2.9 on 2022-04-05 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilemodel',
            name='Family',
        ),
        migrations.RemoveField(
            model_name='profilemodel',
            name='Name',
        ),
    ]
